### ISSUE TITLE
Bug in config.onlyFindTextInsidePaperContour

### ISSUE THREAD

**Issue by Schultzer** [danschultzer/receipt-scanner#15]
### There is a bug in `config.onlyFindTextInsidePaperContour`
when tested agianst test file `readableColor.png` we'll get 
`Uncaught AssertionError: expected [ReferenceError: contours is not defined] to equal null`.

 when tested with `config.onlyFindTextInsidePaperContour` and `config.removeNoise` set to true
` Uncaught AssertionError: expected [ReferenceError: contours is not defined] to equal null`

-

#### Further investigation 
Shows there might be a bug upstream in opencv3 when tested  with `config.onlyFindTextInsidePaperContour` and `config.verbose` set to true

```
OpenCV Error: Assertion failed (count >= 0 && (depth == CV_32F || depth == CV_32S)) in arcLength, file /tmp/opencv3-20160929-23220-ldcoax/modules/imgproc/src/shapedescr.cpp, line 285
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv3-20160929-23220-ldcoax/modules/imgproc/src/shapedescr.cpp:285: error: (-215) count >= 0 && (depth == CV_32F || depth == CV_32S) in function arcLength

Abort trap: 6
```

`config.onlyFindTextInsidePaperContour`, `config.verbose` and `config.removeNoise` set to true

```
OpenCV Error: Assertion failed (count >= 0 && (depth == CV_32F || depth == CV_32S)) in arcLength, file /tmp/opencv3-20160929-23220-ldcoax/modules/imgproc/src/shapedescr.cpp, line 285
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv3-20160929-23220-ldcoax/modules/imgproc/src/shapedescr.cpp:285: error: (-215) count >= 0 && (depth == CV_32F || depth == CV_32S) in function arcLength

Abort trap: 6
```

tests work as expected with `readable.jpg` and `readableGray.png`

-

#### Possible break point `isolatePaper()` 

Changing `cv.Constants.CV_8UC1...cv.Constants.CV_8UC3`
* `cv.Constants.CV_16UC1...cv.Constants.CV_16UC3`
* `cv.Constants.CV_CV_32SC1...cv.Constants.CV_32SC3`
* `cv.Constants.CV_CV_32FC1...cv.Constants.CV_32FC3`

-
##### `readableColor.png`
```
OpenCV Error: Assertion failed (mask.depth() == CV_8U && (mcn == 1 || mcn == cn)) in copyTo, file /tmp/opencv3-20160929-23220-ldcoax/modules/core/src/copy.cpp, line 342
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv3-20160929-23220-ldcoax/modules/core/src/copy.cpp:342: error: (-215) mask.depth() == CV_8U && (mcn == 1 || mcn == cn) in function copyTo

Abort trap: 6
```

##### `readableGray.png`
```
OpenCV Error: Assertion failed (mask.depth() == CV_8U && (mcn == 1 || mcn == cn)) in copyTo, file /tmp/opencv3-20160929-23220-ldcoax/modules/core/src/copy.cpp, line 342
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv3-20160929-23220-ldcoax/modules/core/src/copy.cpp:342: error: (-215) mask.depth() == CV_8U && (mcn == 1 || mcn == cn) in function copyTo

Abort trap: 6
```

`readable.jpg` work as expected

**Comment by danschultzer** [comment]
Where do you change the constants? Does the `png` fail when `config.verbose` is set to `false`?

It would be nice if you could provide a stack trace. It seems like several different issues at once.

--

Looking at the `contours` undefined issue, it's pretty clear what's wrong:

[receipt-scanner/lib/image_processor/preprocessor/opencv-photo2scan.js:171](https://github.com/danschultzer/receipt-scanner/blob/548d95051218c0edcc7e0db53bfaf6c915190e2a/lib/image_processor/preprocessor/opencv-photo2scan.js#L171)
```
function rotate(paperMask, im, outfile, config) {
  contoursList = getTextElementsContours(im);

  if(config.onlyFindTextInsidePaperContour) {
    // This is not necessary unless the paper haven't been deteced
    if (paperMask) {
      var contoursListCountPrevious = contoursList.length;
      // Remove all not inside the paper polygon
      contoursList = contoursList.filter(function(c) {
        points = getContourPoints(contours, c[0]);
        return polygonInPolygon(points, paperMask);
      });
      var removedContoursCount = contoursListCountPrevious - contoursList.length;
      config.log("onlyFindTextInsidePaperContour: Removed " + removedContoursCount + " contours.");
    }
  }
```

---

This is the stack trace for `archLength` call in OpenCV:
  1. [opencv/modules/imgproc/src/shapedscr.cpp:285](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/shapedescr.cpp#L285)
  2. [node-opencv/src/Contours.cc:130](https://github.com/peterbraden/node-opencv/blob/df9959ae7dbfa57fb39147dcb745e67775154b11/src/Contours.cc#L130)
  3. [receipt-scanner/lib/image_processor/preprocessor/opencv-photo2scan.js:277](https://github.com/danschultzer/receipt-scanner/blob/548d95051218c0edcc7e0db53bfaf6c915190e2a/lib/image_processor/preprocessor/opencv-photo2scan.js#L277)

I suspect the reason for the OpenCV exception is because of modifications of the original image. Several places, when `config.verbose` is set to true, the original image is overriding as `im = im.copy();`. There's a lot happening until `config.onlyFindTextInsidePaperContour` is used:

[receipt-scanner/lib/image_processor/preprocessor/opencv-photo2scan.js:22-127](https://github.com/danschultzer/receipt-scanner/blob/548d95051218c0edcc7e0db53bfaf6c915190e2a/lib/image_processor/preprocessor/opencv-photo2scan.js#L22-L27)
```
    var paperMask = findPaperInPhoto(im, outfile, config),
      res = isolatePaper(paperMask, im, outfile, config),
      mask = res[1];
    im = res[0];
    im = warpPerspective(im, mask, outfile, config);
    im = rotate(paperMask, im, outfile, config);
```

Checking each step should give more light to what exactly goes wrong.
