### ISSUE TITLE
npm install or yarn install fails

### ISSUE THREAD

**Issue by Ghost---Shadow** [danschultzer/receipt-scanner#56]
OS information

```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1314
```

Here are the npm logs https://pastebin.com/97xLe4Rn

It looks like node-tesseract is getting timed out.

In `package.json` I tried changing
```
"node-tesseract": "git://github.com/desmondmorris/node-tesseract.git",
"opencv": "git://github.com/peterbraden/node-opencv.git",
```
to

```
 "node-tesseract": "0.2.7",
 "opencv": "6.0.0",
```

but had no luck

Here is the npm log https://pastebin.com/3cvNUSv4

`yarn install` also fails. I can provide logs if required.

**Comment by danschultzer** [comment]
Looks like OpenCV doesn't get compiled. Is OpenCV installed on your system? https://github.com/danschultzer/receipt-scanner#getting-started

**Comment by Ghost---Shadow** [comment]
Yes
```
Warning: opencv 3.4.2 is already installed and up-to-date
To reinstall 3.4.2, run `brew reinstall opencv`
```

**Comment by danschultzer** [comment]
I tried to do a clean install on my system (10.13.6), and it worked just fine.

As you said, the first one does look like you get a timeout on github. Might be a good idea to try run `git ls-remote -h -t git://github.com/desmondmorris/node-tesseract.git` in the terminal to see if you can get the command to work manually at first.

The second npm log work, but probably fails because the old `node-opencv` release won't work.

**Comment by danschultzer** [comment]
I'll close this for now. Let me know if you still experience issues.
